"""update comments table

Revision ID: 05656722da5c
Revises: 56900ae8f390
Create Date: 2025-10-22 10:56:56.920354

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '05656722da5c'
down_revision: Union[str, None] = '56900ae8f390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_platform'), table_name='posts')
    op.drop_index(op.f('ix_posts_platform_id'), table_name='posts')
    op.drop_table('posts')
    op.add_column('comments', sa.Column('intention_analized', sa.Boolean(), nullable=True))
    op.add_column('comments', sa.Column('intention_analized_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('comments', sa.Column('intention', sa.String(length=5), nullable=True))
    op.add_column('comments', sa.Column('intention_confidence', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('comments', 'intention_confidence')
    op.drop_column('comments', 'intention')
    op.drop_column('comments', 'intention_analized_at')
    op.drop_column('comments', 'intention_analized')
    op.create_table('posts',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('platform', postgresql.ENUM('FACEBOOK', 'INSTAGRAM', 'X', 'TRIPADVISOR', name='platformtype'), autoincrement=False, nullable=False),
    sa.Column('platform_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('text', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('media_type', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('media_url', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('platform_created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('posts_pkey'))
    )
    op.create_index(op.f('ix_posts_platform_id'), 'posts', ['platform_id'], unique=True)
    op.create_index(op.f('ix_posts_platform'), 'posts', ['platform'], unique=False)
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    # ### end Alembic commands ###
