"""add crm_lead table

Revision ID: 64999a79a69a
Revises: 18a4f2e6ff7e
Create Date: 2025-11-04 19:27:48.015957

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64999a79a69a'
down_revision: Union[str, None] = '18a4f2e6ff7e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crm_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_score_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('crm_lead_id', sa.String(length=255), nullable=True),
    sa.Column('crm_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', 'UPDATED', name='crmleadstatus'), nullable=False),
    sa.Column('priority_level', sa.String(length=10), nullable=False),
    sa.Column('lead_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('post_url', sa.String(length=512), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('interest', sa.String(length=255), nullable=True),
    sa.Column('instagram_id', sa.Integer(), nullable=True),
    sa.Column('facebook_id', sa.Integer(), nullable=True),
    sa.Column('tripadvisor_id', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('last_sync_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_score_id'], ['lead_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_leads_comment_id'), 'crm_leads', ['comment_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_crm_lead_id'), 'crm_leads', ['crm_lead_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_id'), 'crm_leads', ['id'], unique=False)
    op.create_index(op.f('ix_crm_leads_lead_score_id'), 'crm_leads', ['lead_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_leads_lead_score_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_crm_lead_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_comment_id'), table_name='crm_leads')
    op.drop_table('crm_leads')
    # ### end Alembic commands ###
