"""Add crm_lead table

Revision ID: 1dca1a7a40ae
Revises: 
Create Date: 2025-11-05 17:06:44.293645

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1dca1a7a40ae'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('FACEBOOK', 'INSTAGRAM', 'TRIPADVISOR', name='platformtype'), nullable=False),
    sa.Column('id_comment_platform', sa.String(length=255), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('post_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('platform_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment_analized', sa.Boolean(), nullable=True),
    sa.Column('sentiment_analized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment', sa.String(length=5), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('intention_analized', sa.Boolean(), nullable=True),
    sa.Column('intention_analized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intention', sa.String(length=5), nullable=True),
    sa.Column('intention_confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_id_comment_platform'), 'comments', ['id_comment_platform'], unique=True)
    op.create_index(op.f('ix_comments_platform'), 'comments', ['platform'], unique=False)
    op.create_table('lead_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scoring_version', sa.Text(), nullable=False),
    sa.Column('alpha', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('beta', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('fkw_min', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('fkw_max', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('hot_min', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('warm_min', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('min_intent_for_hot', sa.Numeric(precision=3, scale=2), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_lead_thresholds_id'), 'lead_thresholds', ['id'], unique=False)
    op.create_table('meta_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encrypted_access_token', sa.String(), nullable=False),
    sa.Column('encrypted_page_token', sa.String(), nullable=True),
    sa.Column('fb_page_id', sa.String(), nullable=True),
    sa.Column('ig_business_account_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_credentials_id'), 'meta_credentials', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('FACEBOOK', 'INSTAGRAM', 'TRIPADVISOR', name='platformtype'), nullable=False),
    sa.Column('id_post_platform', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('platform_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_id_post_platform'), 'posts', ['id_post_platform'], unique=True)
    op.create_index(op.f('ix_posts_platform'), 'posts', ['platform'], unique=False)
    op.create_table('lead_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('priority_level', sa.String(length=10), nullable=False),
    sa.Column('scoring_version', sa.Text(), nullable=False),
    sa.Column('computed_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_lead_scores_priority', 'lead_scores', ['priority_level', sa.literal_column('score DESC')], unique=False)
    op.create_index('idx_lead_scores_time', 'lead_scores', [sa.literal_column('computed_at DESC')], unique=False)
    op.create_index(op.f('ix_lead_scores_comment_id'), 'lead_scores', ['comment_id'], unique=True)
    op.create_index(op.f('ix_lead_scores_id'), 'lead_scores', ['id'], unique=False)
    op.create_table('crm_leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('lead_score_id', sa.Integer(), nullable=False),
    sa.Column('comment_id', sa.Integer(), nullable=False),
    sa.Column('crm_lead_id', sa.String(length=255), nullable=True),
    sa.Column('crm_status', sa.Enum('PENDING', 'SYNCED', 'FAILED', 'UPDATED', name='crmleadstatus'), nullable=False),
    sa.Column('priority_level', sa.String(length=10), nullable=False),
    sa.Column('lead_score', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('platform', sa.String(length=50), nullable=False),
    sa.Column('post_url', sa.String(length=512), nullable=True),
    sa.Column('fullname', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=50), nullable=True),
    sa.Column('segment', sa.String(length=100), nullable=True),
    sa.Column('interest', sa.String(length=255), nullable=True),
    sa.Column('instagram_id', sa.Integer(), nullable=True),
    sa.Column('facebook_id', sa.Integer(), nullable=True),
    sa.Column('tripadvisor_id', sa.Integer(), nullable=True),
    sa.Column('synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_error', sa.Text(), nullable=True),
    sa.Column('last_sync_attempt', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sync_attempts', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['comment_id'], ['comments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['lead_score_id'], ['lead_scores.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crm_leads_comment_id'), 'crm_leads', ['comment_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_crm_lead_id'), 'crm_leads', ['crm_lead_id'], unique=False)
    op.create_index(op.f('ix_crm_leads_id'), 'crm_leads', ['id'], unique=False)
    op.create_index(op.f('ix_crm_leads_lead_score_id'), 'crm_leads', ['lead_score_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crm_leads_lead_score_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_crm_lead_id'), table_name='crm_leads')
    op.drop_index(op.f('ix_crm_leads_comment_id'), table_name='crm_leads')
    op.drop_table('crm_leads')
    op.drop_index(op.f('ix_lead_scores_id'), table_name='lead_scores')
    op.drop_index(op.f('ix_lead_scores_comment_id'), table_name='lead_scores')
    op.drop_index('idx_lead_scores_time', table_name='lead_scores')
    op.drop_index('idx_lead_scores_priority', table_name='lead_scores')
    op.drop_table('lead_scores')
    op.drop_index(op.f('ix_posts_platform'), table_name='posts')
    op.drop_index(op.f('ix_posts_id_post_platform'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_meta_credentials_id'), table_name='meta_credentials')
    op.drop_table('meta_credentials')
    op.drop_index(op.f('ix_lead_thresholds_id'), table_name='lead_thresholds')
    op.drop_table('lead_thresholds')
    op.drop_index(op.f('ix_comments_platform'), table_name='comments')
    op.drop_index(op.f('ix_comments_id_comment_platform'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
