"""Add CRMLead table for CRM integration

Revision ID: 9d2182a05504
Revises: b5f103c9a76f
Create Date: 2025-10-30 23:22:07.468133

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d2182a05504'
down_revision: Union[str, None] = 'b5f103c9a76f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
