"""Update Comment model with unified PlatformType enum

Revision ID: 9aba0ccf222d
Revises: 64999a79a69a
Create Date: 2025-11-04 23:38:46.320055

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9aba0ccf222d'
down_revision: Union[str, None] = '64999a79a69a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('comments', 'id_comment_platform',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=255),
               nullable=False)
    op.drop_index(op.f('ix_comments_platform_id'), table_name='comments')
    op.create_index(op.f('ix_comments_id_comment_platform'), 'comments', ['id_comment_platform'], unique=True)
    op.drop_column('comments', 'platform_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('comments', sa.Column('platform_id', sa.VARCHAR(length=255), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_comments_id_comment_platform'), table_name='comments')
    op.create_index(op.f('ix_comments_platform_id'), 'comments', ['platform_id'], unique=True)
    op.alter_column('comments', 'id_comment_platform',
               existing_type=sa.String(length=255),
               type_=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
