"""Initial migration with all tables

Revision ID: edfd62c64c07
Revises: 
Create Date: 2025-10-23 01:03:12.646981

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'edfd62c64c07'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'tripadvisor', name='platformtype'), nullable=False),
    sa.Column('platform_id', sa.String(length=255), nullable=False),
    sa.Column('id_comment_platform', sa.Integer(), nullable=True),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('post_url', sa.String(length=512), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('platform_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment_analized', sa.Boolean(), nullable=True),
    sa.Column('sentiment_analized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sentiment', sa.String(length=5), nullable=True),
    sa.Column('sentiment_confidence', sa.Float(), nullable=True),
    sa.Column('intention_analized', sa.Boolean(), nullable=True),
    sa.Column('intention_analized_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('intention', sa.String(length=5), nullable=True),
    sa.Column('intention_confidence', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_comments_id'), 'comments', ['id'], unique=False)
    op.create_index(op.f('ix_comments_platform'), 'comments', ['platform'], unique=False)
    op.create_index(op.f('ix_comments_platform_id'), 'comments', ['platform_id'], unique=True)
    op.create_table('meta_credentials',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('encrypted_access_token', sa.String(), nullable=False),
    sa.Column('fb_page_id', sa.String(), nullable=True),
    sa.Column('ig_business_account_id', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_meta_credentials_id'), 'meta_credentials', ['id'], unique=False)
    op.create_table('posts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('platform', sa.Enum('facebook', 'instagram', 'tripadvisor', name='platformtype'), nullable=False),
    sa.Column('platform_id', sa.String(length=255), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('media_type', sa.String(), nullable=True),
    sa.Column('media_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('platform_created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_posts_id'), 'posts', ['id'], unique=False)
    op.create_index(op.f('ix_posts_platform'), 'posts', ['platform'], unique=False)
    op.create_index(op.f('ix_posts_platform_id'), 'posts', ['platform_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_platform_id'), table_name='posts')
    op.drop_index(op.f('ix_posts_platform'), table_name='posts')
    op.drop_index(op.f('ix_posts_id'), table_name='posts')
    op.drop_table('posts')
    op.drop_index(op.f('ix_meta_credentials_id'), table_name='meta_credentials')
    op.drop_table('meta_credentials')
    op.drop_index(op.f('ix_comments_platform_id'), table_name='comments')
    op.drop_index(op.f('ix_comments_platform'), table_name='comments')
    op.drop_index(op.f('ix_comments_id'), table_name='comments')
    op.drop_table('comments')
    # ### end Alembic commands ###
