"""create users and posts tables

Revision ID: dee39d8a80ba
Revises: 1dca1a7a40ae
Create Date: 2025-11-05 18:14:11.185825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dee39d8a80ba'
down_revision: Union[str, None] = '1dca1a7a40ae'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crm_leads', 'lead_score_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crm_leads', 'comment_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('crm_leads', 'priority_level',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    op.alter_column('crm_leads', 'lead_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=True)
    op.alter_column('crm_leads', 'content',
               existing_type=sa.TEXT(),
               nullable=True)
    op.alter_column('crm_leads', 'interest',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.Text(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('crm_leads', 'interest',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
    op.alter_column('crm_leads', 'content',
               existing_type=sa.TEXT(),
               nullable=False)
    op.alter_column('crm_leads', 'lead_score',
               existing_type=sa.NUMERIC(precision=5, scale=2),
               nullable=False)
    op.alter_column('crm_leads', 'priority_level',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('crm_leads', 'comment_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('crm_leads', 'lead_score_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
